name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build lib
      run: cargo build --verbose --no-default-features
    - name: Build bin
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run examples tests
      run: cargo test --verbose --examples
    - name: Run lints
      run: cargo clippy --verbose -- -D warnings
    - name: Run examples lints
      run: cargo clippy --verbose --examples -- -D warnings
