name: tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install nightly toolchain
      run: rustup toolchain install nightly --component clippy
    - name: Install stable toolchain
      run: rustup toolchain install stable --component llvm-tools-preview
    - uses: Swatinem/rust-cache@v2
    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@cargo-llvm-cov
    - name: Build lib
      run: cargo build --verbose --no-default-features
    - name: Build bin
      run: cargo build --verbose
    - name: Run tests with coverage
      run: cargo llvm-cov --lib --tests --examples --fail-under-lines 90
    - name: Run doctests
      run: cargo test --doc --verbose
    - name: Run lints
      run: cargo +nightly clippy --verbose --all-targets --all-features -- -D warnings
